<div style="font-size:18pt; padding-top:20px; text-align:center">СЕМИНАР 16. <b>Объединение деревьев и </b> <span style="font-weight:bold; color:green">NumPy/SciPy/Sklearn</span></div><hr>
<div style="text-align:right;">Папулин С.Ю. <span style="font-style: italic;font-weight: bold;">(papulin_hse@mail.ru)</span></div>

<a name="0"></a>
<div><span style="font-size:14pt; font-weight:bold">Содержание</span>
    <ol>
        <li><a href="#1">Преобразование категориальных значений</a></li>
        <li><a href="#2">Решающее дерево c категориальными признаками</a></li>
        <li><a href="#3">Источники</a>
        </li>
    </ol>
</div>

<p><b>Подлючение библиотек</b></p>

In [1]:
import time
import numpy as np
import pandas as pnd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from scipy import stats

In [6]:
from sklearn import cross_validation

In [7]:
from sklearn.datasets import make_classification
from matplotlib import cm
from matplotlib.colors import ListedColormap

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import LabelEncoder

In [9]:
from sklearn import tree

<a name="1"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">1. Преобразование категориальных значений</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

<p><b>Преобразование категориальных признаков</b></p>

In [10]:
from sklearn.feature_extraction import DictVectorizer

In [11]:
from sklearn.preprocessing import OneHotEncoder

<p><b><i>Один признак</i></b></p>

In [12]:
x = np.array(["red", "green", "blue", "red", "red", "green", "blue", "blue"])

<p><b><a href="http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html">
DictVectorizer</a></b></p>

In [13]:
x_d = [{"color": el} for el in x]
x_d

[{'color': 'red'},
 {'color': 'green'},
 {'color': 'blue'},
 {'color': 'red'},
 {'color': 'red'},
 {'color': 'green'},
 {'color': 'blue'},
 {'color': 'blue'}]

In [14]:
dv = DictVectorizer(sparse=False)
x_dv = dv.fit_transform(x_d)
x_dv

array([[ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

<p><b><a href="http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html">
OneHotEncoder</a></b></p>

In [15]:
x_dval = { value:indx for indx, value in enumerate(np.unique(x))}
x_dval

{'blue': 0, 'green': 1, 'red': 2}

In [16]:
x_num = np.array([x_dval[el] for el in x])
x_num

array([2, 1, 0, 2, 2, 1, 0, 0])

In [17]:
xx = x_num[:, np.newaxis]
xx

array([[2],
       [1],
       [0],
       [2],
       [2],
       [1],
       [0],
       [0]])

In [19]:
enc = OneHotEncoder()
enc.fit_transform(xx).toarray()

array([[ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

<p><b><i>Два признака</i></b></p>

In [20]:
x1 = np.array(["red", "green", "blue", "red", "red", "green", "blue", "blue"])
x2 = np.array(["yes", "no", "yes", "yes", "no", "yes", "no", "yes"])

<p><b><a href="http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html">
DictVectorizer</a></b></p>

In [21]:
x12 = list(zip(x1,x2))
x12

[('red', 'yes'),
 ('green', 'no'),
 ('blue', 'yes'),
 ('red', 'yes'),
 ('red', 'no'),
 ('green', 'yes'),
 ('blue', 'no'),
 ('blue', 'yes')]

In [22]:
x12_d = [{"color": el[0], "mood": el[1]} for el in x12]
x12_d

[{'color': 'red', 'mood': 'yes'},
 {'color': 'green', 'mood': 'no'},
 {'color': 'blue', 'mood': 'yes'},
 {'color': 'red', 'mood': 'yes'},
 {'color': 'red', 'mood': 'no'},
 {'color': 'green', 'mood': 'yes'},
 {'color': 'blue', 'mood': 'no'},
 {'color': 'blue', 'mood': 'yes'}]

In [23]:
dv = DictVectorizer(sparse=False)
x12_dv = dv.fit_transform(x12_d)
x12_dv

array([[ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.]])

<p><b><a href="http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html">
OneHotEncoder</a></b></p>

In [24]:
x12

[('red', 'yes'),
 ('green', 'no'),
 ('blue', 'yes'),
 ('red', 'yes'),
 ('red', 'no'),
 ('green', 'yes'),
 ('blue', 'no'),
 ('blue', 'yes')]

In [25]:
x1d = { value:indx for indx, value in enumerate(np.unique(x1))}
x2d = { value:indx for indx, value in enumerate(np.unique(x2))}

x12_dval = np.array([(x1d[el[0]], x2d[el[1]]) for el in x12])
x12_dval

array([[2, 1],
       [1, 0],
       [0, 1],
       [2, 1],
       [2, 0],
       [1, 1],
       [0, 0],
       [0, 1]])

In [27]:
enc = OneHotEncoder()
enc.fit_transform(x12_dval).toarray()

array([[ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.]])

<p><b>Преобразование категориальных значений принадлежности классу</b></p>

In [28]:
y = ["full", "half", "empty", "full", "full", "half", "empty"]

<p><b><a href="http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html">
LabelEncoder</a></b></p>

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
le = LabelEncoder()

In [31]:
le = le.fit(y)

In [32]:
le.classes_

array(['empty', 'full', 'half'], 
      dtype='<U5')

In [33]:
le.transform(y)

array([1, 2, 0, 1, 1, 2, 0], dtype=int64)

In [34]:
le.transform(["empty", "half", "half", "full"])

array([0, 2, 2, 1], dtype=int64)

In [35]:
le.inverse_transform([0, 2, 2, 1])

array(['empty', 'half', 'half', 'full'], 
      dtype='<U5')

<a name="2"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">2. Решающее дерево c категориальными признаками</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [36]:
from sklearn.feature_extraction import DictVectorizer

<p><b>Исходные данные</b></p>

In [38]:
df = pnd.read_csv("vertebrate.csv")
df.dropna(inplace=True)
df.head(5)

Name Body Temperature Skin Cover Gives Birth Aquatic Creature  \
0   human     warm-blooded       hair         yes               no   
1  python     cold-blooded     scales          no               no   
2  salmon     cold-blooded     scales          no              yes   
3   whale     warm-blooded       hair         yes              yes   
4    frog     cold-blooded       none          no             semi   

  Aerial Creature Has Legs Hibernates Class Label  
0              no      yes         no      mammal  
1              no       no        yes     reptile  
2              no       no         no        fish  
3              no       no         no      mammal  
4              no      yes        yes   amphibian

<p><b>Предобработка</b></p>

<p><b><i>Признаки</i></b></p>

In [39]:
X = df[df.columns[1:8]]
X.head(5)

Body Temperature Skin Cover Gives Birth Aquatic Creature Aerial Creature  \
0     warm-blooded       hair         yes               no              no   
1     cold-blooded     scales          no               no              no   
2     cold-blooded     scales          no              yes              no   
3     warm-blooded       hair         yes              yes              no   
4     cold-blooded       none          no             semi              no   

  Has Legs Hibernates  
0      yes         no  
1       no        yes  
2       no         no  
3       no         no  
4      yes        yes

In [40]:
X_d = X.to_dict(orient="record")
X_d[:2]

[{'Aerial Creature': 'no',
  'Aquatic Creature': 'no',
  'Body Temperature': 'warm-blooded',
  'Gives Birth': 'yes',
  'Has Legs': 'yes',
  'Hibernates': 'no',
  'Skin Cover': 'hair'},
 {'Aerial Creature': 'no',
  'Aquatic Creature': 'no',
  'Body Temperature': 'cold-blooded',
  'Gives Birth': 'no',
  'Has Legs': 'no',
  'Hibernates': 'yes',
  'Skin Cover': 'scales'}]

In [41]:
dv = DictVectorizer(sparse=False)
X_dv = dv.fit_transform(X_d)
X_dv[:2]

array([[ 1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  1.]])

<p><b><i>Классы</i></b></p>

In [42]:
Y = df["Class Label"]
Y

0        mammal
1       reptile
2          fish
3        mammal
4     amphibian
5       reptile
6        mammal
7          bird
8        mammal
9          fish
10      reptile
11         bird
12       mammal
13         fish
14    amphibian
Name: Class Label, dtype: object

In [43]:
le = LabelEncoder()

In [44]:
Y_le = le.fit_transform(Y)
Y_le

array([3, 4, 2, 3, 0, 4, 3, 1, 3, 2, 4, 1, 3, 2, 0], dtype=int64)

In [45]:
le.inverse_transform([3, 4, 2, 3, 0, 4, 3, 1, 3, 2, 4, 1, 3, 2, 0])

array(['mammal', 'reptile', 'fish', 'mammal', 'amphibian', 'reptile',
       'mammal', 'bird', 'mammal', 'fish', 'reptile', 'bird', 'mammal',
       'fish', 'amphibian'], dtype=object)

<p><b>Формирование обучающего и тестового подмножеств</b></p>

In [46]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(X_dv, Y_le, test_size=0, random_state=0)

<p><b>Обучение</b></p>

In [47]:
decTree = tree.DecisionTreeClassifier(criterion="entropy")

In [48]:
decTree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [49]:
score = decTree.score(x_train, y_train)
score

1.0

<p><b>Простая проверка</b></p>

In [50]:
x_test_arr = ["cold-blooded", "scales", "no", "no", "no", "no", "yes"]
X_test_d = {df.columns[1:8][i]:x_test_arr[i] for i in range(len(x_test_arr))}
X_test_d

{'Aerial Creature': 'no',
 'Aquatic Creature': 'no',
 'Body Temperature': 'cold-blooded',
 'Gives Birth': 'no',
 'Has Legs': 'no',
 'Hibernates': 'yes',
 'Skin Cover': 'scales'}

In [51]:
#x_test_arr = ["cold-blooded", "scales", "no", "no", "no", "no", "yes"]
#x_zip = list(zip(df.columns[1:8], x_test_arr))
#X_test_d = {el[0]:el[1] for el in x_zip}
#X_test_d

In [52]:
X_test = dv.transform(X_test_d)
X_test

array([[ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  1.]])

In [53]:
pr_value = decTree.predict(X_test)
pr_value

array([4], dtype=int64)

In [54]:
le.inverse_transform(pr_value)

array(['reptile'], dtype=object)

<p><b>Пример 2</b></p>

http://archive.ics.uci.edu/ml/datasets/Car+Evaluation

<a name="3"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">3. Источники</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>