<div style="font-size:18pt; padding-top:20px; text-align:center">СЕМИНАР 14. <b>Выбор признаков и </b> <span style="font-weight:bold; color:green">NumPy/SciPy/Sklearn</span></div><hr>
<div style="text-align:right;">Папулин С.Ю. <span style="font-style: italic;font-weight: bold;">(papulin_hse@mail.ru)</span></div>

<a name="0"></a>
<div><span style="font-size:14pt; font-weight:bold">Содержание</span>
    <ol>
        <li><a href="#1">Удаление признаков с небольшим разбросом (Removing features with low variance)</a></li>
        <li><a href="#2">Одномерный отбор признаков (Univariate feature selection)</a></li>
        <li><a href="#3">Рекурсивное исключение признаков (Recursive feature elimination)</a></li>
        <li><a href="#4">Выбор признаков с SelectFromModel</a></li>
        <li><a href="#5">Источники</a>
        </li>
    </ol>
</div>

<p><b>Подлючение библиотек</b></p>

In [1]:
import time
import numpy as np
import pandas as pnd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.pipeline import Pipeline

In [3]:
from sklearn.datasets import make_classification
from matplotlib import cm
from matplotlib.colors import ListedColormap

<a name="1"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">1. Удаление признаков с небольшим разбросом </div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [4]:
from sklearn.feature_selection import VarianceThreshold

In [5]:
X = [[0, 0, 1], 
     [0, 1, 0], 
     [1, 0, 0], 
     [0, 1, 1], 
     [0, 1, 0], 
     [0, 1, 1]]
sel = VarianceThreshold(threshold=(0.8*(1-0.8)))
sel.fit_transform(X) #вероятность попадания 0 или 1 больше 80%

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])

In [ ]:
#то что меньше - удаляет

In [6]:
X = [[0, 2, 0, 3], 
     [0, 1, 4, 3], 
     [0, 1, 1, 3]]
sel = VarianceThreshold()
sel.fit_transform(X)

array([[2, 0],
       [1, 4],
       [1, 1]])

<a name="2"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">2. Одномерный отбор признаков</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [7]:
from sklearn.feature_selection import SelectKBest

<p><b>Классификация</b></p>

In [8]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

In [9]:
from sklearn.feature_selection import chi2 #chi-squared stats
from sklearn.feature_selection import f_classif #ANOVA F-value

In [10]:
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

In [23]:
print(iris.DESCR)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#chi2(X[:,0, np.newaxis], y)

In [14]:
fs = SelectKBest(chi2, k=2)#выбор 2 признаков

In [15]:
X_new = fs.fit_transform(X, y)
X_new.shape

(150, 2)

In [16]:
fs.scores_

array([  10.81782088,    3.59449902,  116.16984746,   67.24482759])

In [17]:
fs.pvalues_

array([  4.47651499e-03,   1.65754167e-01,   5.94344354e-26,
         2.50017968e-15])

In [20]:
from sklearn.linear_model import LogisticRegression

In [18]:
X_new

array([[ 1.4,  0.2],
       [ 1.4,  0.2],
       [ 1.3,  0.2],
       [ 1.5,  0.2],
       [ 1.4,  0.2],
       [ 1.7,  0.4],
       [ 1.4,  0.3],
       [ 1.5,  0.2],
       [ 1.4,  0.2],
       [ 1.5,  0.1],
       [ 1.5,  0.2],
       [ 1.6,  0.2],
       [ 1.4,  0.1],
       [ 1.1,  0.1],
       [ 1.2,  0.2],
       [ 1.5,  0.4],
       [ 1.3,  0.4],
       [ 1.4,  0.3],
       [ 1.7,  0.3],
       [ 1.5,  0.3],
       [ 1.7,  0.2],
       [ 1.5,  0.4],
       [ 1. ,  0.2],
       [ 1.7,  0.5],
       [ 1.9,  0.2],
       [ 1.6,  0.2],
       [ 1.6,  0.4],
       [ 1.5,  0.2],
       [ 1.4,  0.2],
       [ 1.6,  0.2],
       [ 1.6,  0.2],
       [ 1.5,  0.4],
       [ 1.5,  0.1],
       [ 1.4,  0.2],
       [ 1.5,  0.1],
       [ 1.2,  0.2],
       [ 1.3,  0.2],
       [ 1.5,  0.1],
       [ 1.3,  0.2],
       [ 1.5,  0.2],
       [ 1.3,  0.3],
       [ 1.3,  0.3],
       [ 1.3,  0.2],
       [ 1.6,  0.6],
       [ 1.9,  0.4],
       [ 1.4,  0.3],
       [ 1.6,  0.2],
       [ 1.4,

In [35]:
#сравнение accuracy для 4 и 2 признаков
logreg = LogisticRegression(penalty = "l1",C=3)
logreg4 = logreg.fit(X,y)
print("Score for 4 param. = {}".format(logreg4.score(X,y)))
logreg2 = logreg.fit(X_new,y)
print("Score for 2 param. = {}".format(logreg2.score(X_new,y)))

Score for 4 param. = 0.98
Score for 2 param. = 0.96


In [ ]:
#xn0 = np.array([X[i,0] for i in range(len(y)) if y[i]==0])
#xp0 = np.array([X[i,0]  for i in range(len(y)) if y[i]==1])
#
#xn1 = np.array([X[i,1] for i in range(len(y)) if y[i]==0])
#xp1 = np.array([X[i,1]  for i in range(len(y)) if y[i]==1])
#
#xn2 = np.array([X[i,2] for i in range(len(y)) if y[i]==0])
#xp2 = np.array([X[i,2]  for i in range(len(y)) if y[i]==1])
#
#xn3 = np.array([X[i,3] for i in range(len(y)) if y[i]==0])
#xp3 = np.array([X[i,3]  for i in range(len(y)) if y[i]==1])

In [ ]:
#xn0, xp0

In [ ]:
#m_xn0 = xn0.mean()
#m_xp0 = xp0.mean()
#m_xn1 = xn1.mean()
#m_xp1 = xp1.mean()
#m_xn2 = xn2.mean()
#m_xp2 = xp2.mean()
#m_xn3 = xn3.mean()
#m_xp3 = xp3.mean()

In [ ]:
#sum((xn0 - m_xn0)**2 / m_xn0)

In [ ]:
#sum((xp0 - m_xp0)**2 / m_xp0)

In [ ]:
#m = np.array([[m_xn0, m_xp0],[m_xn1, m_xp1],[m_xn2, m_xp2], [m_xn3, m_xp3]])
#m

In [ ]:
#mm_n = sum(xn0)/sum(X[:,0])
#mm_n

In [ ]:
#sum((xn0 - mm_n)**2/(mm_n))

In [ ]:
#149*X[:,0].var()

In [ ]:
#np.array(list(zip()))

In [ ]:
#sum((X[:,0] - X[:,0].mean())**2/X[:,0].var())

In [ ]:
#chi2(X, y)

In [ ]:
#ob = np.array([29, 24, 22, 19, 21, 18, 19, 20, 23, 18, 20, 23])

In [ ]:
#ex = ob.mean()
#ex

In [ ]:
#sum((ob-ob.mean())**2/ob.mean())

<p>Пример с классификацией</p>

In [ ]:
clf = Pipeline([('feature_selection', SelectKBest(chi2, k=2)), ('classification', RandomForestClassifier())])
clf.fit(X, y)

<p><b>Регрессия</b></p>

In [36]:
from sklearn.datasets import load_boston

In [37]:
from sklearn.feature_selection import f_regression

In [38]:
bost = load_boston()
X, y = bost.data, bost.target
X.shape

(506, 13)

In [39]:
X_new = SelectKBest(f_regression, k=2).fit_transform(X, y)
X_new.shape

(506, 2)

In [56]:
from sklearn.linear_model import LinearRegression
linreg13 = LinearRegression(fit_intercept = True, normalize = True)
linreg4 = LinearRegression(fit_intercept = True, normalize = True)
linreg13 = linreg13.fit(X,y)
linreg4 = linreg4.fit(X_new,y)
print("Score for 13: {}".format(linreg13.score(X,y)))
print("Score for 13: {}".format(linreg4.score(X_new,y)))

ValueError: Found input variables with inconsistent numbers of samples: [6578, 506]

<p>Пример с регрессией</p>

<a name="3"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">3. Рекурсивное исключение признаков</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [57]:
from sklearn.datasets import make_friedman1
from sklearn.linear_model import LinearRegression

In [58]:
from sklearn.feature_selection import RFE

In [59]:
X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)
X.shape

(50, 10)

In [60]:
lReg = LinearRegression()

In [62]:
sel = RFE(lReg, 5, step=1) #step - кол-во признаков, которые отбрасываем за шаг
sel.fit_transform(X, y)

array([[ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ],
       [ 0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606],
       [ 0.97861834,  0.79915856,  0.46147936,  0.78052918,  0.11827443],
       [ 0.26455561,  0.77423369,  0.45615033,  0.56843395,  0.0187898 ],
       [ 0.3595079 ,  0.43703195,  0.6976312 ,  0.06022547,  0.66676672],
       [ 0.57019677,  0.43860151,  0.98837384,  0.10204481,  0.20887676],
       [ 0.15896958,  0.11037514,  0.65632959,  0.13818295,  0.19658236],
       [ 0.97645947,  0.4686512 ,  0.97676109,  0.60484552,  0.73926358],
       [ 0.31798318,  0.41426299,  0.0641475 ,  0.69247212,  0.56660145],
       [ 0.31856895,  0.66741038,  0.13179786,  0.7163272 ,  0.28940609],
       [ 0.67781654,  0.27000797,  0.73519402,  0.96218855,  0.24875314],
       [ 0.44712538,  0.84640867,  0.69947928,  0.29743695,  0.81379782],
       [ 0.72525428,  0.50132438,  0.95608363,  0.6439902 ,  0.42385505],
       [ 0.61801543,  0.4287687 ,  0.1

<p>Пример с классификацией</p>

In [63]:
from sklearn.datasets import load_iris

In [64]:
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

<p>Пример с регрессией</p>

In [65]:
from sklearn.datasets import load_diabetes

In [66]:
diab = load_diabetes()
X, y = diab.data, diab.target
X.shape

(442, 10)

<a name="4"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">4. Выбор признаков с SelectFromModel</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [67]:
from sklearn.datasets import load_iris

In [68]:
from sklearn.ensemble import ExtraTreesClassifier

In [69]:
from sklearn.feature_selection import SelectFromModel

In [70]:
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

In [71]:
cETC = ExtraTreesClassifier()
cETC = cETC.fit(X, y)
cETC.feature_importances_  #вес каждого признака при работе с моделью

array([ 0.13953877,  0.08292947,  0.42198585,  0.3555459 ])

In [72]:
selModel = SelectFromModel(cETC, prefit=True)
X_new = selModel.transform(X)
X_new.shape  

(150, 2)

<a name="5"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">5. PCA</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [73]:
from sklearn.decomposition import PCA
X = np.array([[-1, -1], 
              [-2, -1], 
              [-3, -2], 
              [1, 1], 
              [2, 1], 
              [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)
PCA(copy=True, n_components=2, whiten=False)
print(pca.explained_variance_ratio_) 

[ 0.99244289  0.00755711]


<a name="6"></a>
<div style="display:table; width:100%; padding-top:10px; padding-bottom:10px; border-bottom:1px solid lightgrey">
    <div style="display:table-row">
        <div style="display:table-cell; width:80%; font-size:14pt; font-weight:bold">6. Источники</div>
    	<div style="display:table-cell; width:20%; text-align:center; background-color:whitesmoke; border:1px solid lightgrey"><a href="#0">К содержанию</a></div>
    </div>
</div>

In [ ]:
http://scikit-learn.org/stable/modules/feature_selection.html